name: AWS OIDC Test

on: push

permissions:
  id-token: write
  contents: read

jobs:
  oidc-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsTest
          aws-region: ap-northeast-1

      - name: Get AWS Login Info
        run: aws sts get-caller-identity

      - name: Get S3 list
        run: aws s3 ls
